customhost = "students.cjstsbv4obus.eu-north-1.rds.amazonaws.com"
customuser = "madhu29"
custompass = "MAmo2908#**"
customdb = "students"
custombucket = "aws-studbuck"
customregion = "eu-north-1"
customtable = "students"
