customhost = "student.cjstsbv4obus.eu-north-1.rds.amazonaws.com"
customuser = "madhu29"
custompass = "MAmo2908#**"
customdb = "student"
custombucket = "studbuck"
customregion = "us-east-2"
customtable = "student"
